let timeEl = document.getElementById("time");
let quoteEl = document.getElementById("quote");
let content = document.getElementById("content");
let periodEl = document.querySelector(".period");
let bar = document.getElementById("fill");

let quotes = {
  0: {
    0: "Still awake? Bold of you.",
    1: "This hour doesn’t exist unless you’re stressed.",
    2: "Why are you even reading this at midnight?",
    3: "The day is over. Let it go.",
    4: "Midnight snacks don't judge you.",
    5: "It’s okay to cry under the covers.",
    6: "Don’t worry, tomorrow’s you will fix it. Maybe.",
    7: "Scroll one more time. Regret one more time.",
    8: "Deep night thoughts = bad decisions.",
    9: "The world is asleep. You should be too.",
    10: "Is that the sun or your screen?",
    11: "At least you're not emailing someone right now.",
    12: "2AM you has nothing to do with 9AM you.",
    13: "Write that text. Or don’t.",
    14: "This hour is brought to you by insomnia.",
    15: "Even ghosts clock out by now.",
    16: "You're just a little mysterious, that's all.",
    17: "Do not online shop. I repeat, do not online shop.",
    18: "Blankets fix nothing but they help everything.",
    19: "You said you'd sleep early.",
    20: "This is just bonus tomorrow fatigue.",
    21: "Should you be journaling? Nah, binge instead.",
    22: "A nap right now? Yes. Life nap? Not yet.",
    23: "You are not the only one still awake.",
    24: "Look at you, glowing in screen light.",
    25: "Shhh. Even your problems are asleep.",
    26: "This is your brain on vibes.",
    27: "Even the moon is like... seriously?",
    28: "Try blinking. Like actually.",
    29: "Too early to be up, too late to care.",
    30: "You’re the main character. Just tired.",
    31: "If you screenshot this, seek help.",
    32: "Stretch your back. Your spine needs you.",
    33: "Another episode? Brave.",
    34: "Is that a bird or just your exhaustion?",
    35: "Hydrate or lie dramatically on the floor.",
    36: "1AM and you're glowing. Not healthy.",
    37: "Your pillow misses you.",
    38: "It's not that deep. Go to sleep.",
    39: "This hour smells like regret and chips.",
    40: "Even your alarm is worried about you.",
    41: "Your room is louder at 1AM. Weird, huh?",
    42: "No one will know if you sleep now.",
    43: "You're officially nocturnal now.",
    44: "If you're reading this, blink twice.",
    45: "Everything is content. Even your breakdown.",
    46: "This is fine. Everything's fine.",
    47: "You're basically in another time zone now.",
    48: "No sleep = more character development.",
    49: "Congrats, you’re tomorrow’s problem.",
    50: "Silence is loudest at this hour.",
    51: "Eat something reasonable. Not ice cream.",
    52: "No one: ... You: still awake at 2.",
    53: "You said you'd sleep 3 hours ago.",
    54: "This hour isn’t real. You aren’t real.",
    55: "If your phone battery dies, so will you (emotionally).",
    56: "Existential hour has entered the chat.",
    57: "Sleep is temporary, chaos is forever.",
    58: "Watch the clock. Feel the dread.",
    59: "Snooze life. Permanently."
  }
};

quotes[1] = {
  0: "One more scroll. Just one more.",
  1: "Your sleep schedule left the chat.",
  2: "That notification was imaginary.",
  3: "You're not tired, you're dramatic.",
  4: "Time feels fake right now.",
  5: "If vibes were currency, you'd be rich.",
  6: "Replaying conversations from 2016? Classic.",
  7: "You blinked too long. That was a nap.",
  8: "Why is 1 AM so emotionally loud?",
  9: "This isn’t a bad decision yet… but it’s close.",
  10: "The ceiling is very judgmental tonight.",
  11: "Your dreams are buffering.",
  12: "You versus the urge to reinvent your life.",
  13: "This is not peak productivity hour. Stop.",
  14: "You said goodnight hours ago.",
  15: "This playlist is hitting too hard.",
  16: "Yes, your bed does feel extra existential now.",
  17: "Your brain wants answers. Your body wants sleep.",
  18: "You're arguing with imaginary people again.",
  19: "Insomnia: the deluxe subscription.",
  20: "You’re not alone. Everyone’s awake and sad.",
  21: "That idea can wait. No, seriously. Sleep.",
  22: "If your blanket feels like a hug, thank it.",
  23: "You’re speedrunning sleep deprivation.",
  24: "You should be dreaming, not refreshing.",
  25: "The world won’t collapse if you go offline.",
  26: "1 AM is not for clarity. It’s for chaos.",
  27: "Mood swings: now in high resolution.",
  28: "Every deep thought tonight is suspicious.",
  29: "The fridge is whispering again.",
  30: "If your brain had a whiteboard, it's full.",
  31: "Sleep. Not just a concept anymore.",
  32: "You're not solving your life tonight.",
  33: "Reminder: ghosts prefer silence.",
  34: "Why do shadows look extra dramatic now?",
  35: "No one needs your hot take at 1:35 AM.",
  36: "Maybe you’re the ghost now.",
  37: "Let the bed win.",
  38: "At least you’re hydrated… right?",
  39: "Who needs rest when you have overthinking?",
  40: "The future can wait. Dreams can't.",
  41: "You're not lazy. You're just 1AM-ing.",
  42: "Did you just rewatch your life in your head?",
  43: "Plot twist: you’re fine. Just tired.",
  44: "Sleep is rebellious now.",
  45: "You're still a legend. Just horizontal.",
  46: "Congrats, you're now nocturnal royalty.",
  47: "Your bed misses you. Make up.",
  48: "This mood? Sponsored by exhaustion.",
  49: "1 AM thoughts: profound but suspicious.",
  50: "You've entered the soft spiral zone.",
  51: "Eyes open. Brain loud. Soul tired.",
  52: "Night owl? More like night gremlin.",
  53: "Shhh. Even your chaos needs rest.",
  54: "Your inner monologue is now yelling.",
  55: "Breathe. You’re allowed to log off.",
  56: "Sleep won’t fix everything. But it’s a start.",
  57: "Even your playlists want you to rest.",
  58: "You're tired in HD.",
  59: "Let the quote end, and your sleep begin."
};

quotes[2] = {
  0: "You’re not okay, but you are hilarious.",
  1: "At 2AM, every problem is a personality trait.",
  2: "No one warned you about this hour’s honesty.",
  3: "Even your thoughts have echo now.",
  4: "2AM is just midnight’s anxious cousin.",
  5: "You’re not even doomscrolling — you’re freescrolling.",
  6: "You blinked and unlocked level 2 of insomnia.",
  7: "Congratulations. You’ve passed bedtime.",
  8: "Does thinking count as cardio? Asking for you.",
  9: "Yes, your pillow is your therapist now.",
  10: "There’s no plot. Just vibes and blurry eyes.",
  11: "Your phone is hot. Your brain is hotter.",
  12: "The silence is not empty — it’s judgmental.",
  13: "You’re 85% caffeine, 15% memory at this point.",
  14: "This is either self-care or sabotage.",
  15: "Time doesn’t pass — it stretches.",
  16: "Who even needs REM cycles anyway?",
  17: "Yes, that was the floor creaking. Or a ghost.",
  18: "You’d win a gold medal in overthinking.",
  19: "Every tab open is a piece of your soul.",
  20: "This song hits different at 2:20 AM.",
  21: "Reality feels like a screensaver right now.",
  22: "No worries. You’ll regret this later.",
  23: "Go ahead, romanticize your suffering.",
  24: "If overanalysis burned calories, you'd be shredded.",
  25: "You’re three Googles away from a life crisis.",
  26: "Everything’s too loud and too quiet at once.",
  27: "This is the plot twist nobody asked for.",
  28: "The moon is watching you spiral.",
  29: "You're running on chaos and notifications.",
  30: "Honestly? You're killing it. Slowly.",
  31: "Even your reflection wants you to sleep.",
  32: "Your contacts gave up. Why haven’t you?",
  33: "If vibes were medicine, you'd be overdosed.",
  34: "This isn’t a mood. It’s a full-blown novella.",
  35: "Your phone is now 98% forehead grease.",
  36: "You googled 'why am I like this'. Again.",
  37: "Whatever you're doing... stop. Hug a pillow.",
  38: "You're not alone. Just... very online.",
  39: "This is your sign to log off.",
  40: "2AM you deserves a gentle forehead kiss.",
  41: "Deep breath. This isn’t the final version of you.",
  42: "You’ve rewatched that reel 19 times. Move on.",
  43: "Maybe the real rest was the nap we didn’t take.",
  44: "Reality is buffering. Please wait.",
  45: "Your next big idea is hiding in a yawn.",
  46: "The shadows on your ceiling have names now.",
  47: "Every inhale sounds dramatic tonight.",
  48: "You're not crying. Just... blinking really wet.",
  49: "You were supposed to sleep. Not narrate your trauma.",
  50: "Nothing hits harder than 2AM clarity. Except maybe a truck.",
  51: "You're just raw footage at this point.",
  52: "If you email someone now, you're a menace.",
  53: "Time is fake and so are you (a little).",
  54: "This is fine. This is a little flaming fine.",
  55: "You’d delete your brain’s search history if you could.",
  56: "Blink twice if you need water. Or help.",
  57: "A night like this belongs in a playlist.",
  58: "Soft spiral loading... complete.",
  59: "Sleep won’t solve everything. But neither will staying up."
};

quotes[3] = {
  0: "3AM is when the truth leaks out in lowercase.",
  1: "If you feel haunted, it's probably yourself.",
  2: "You're not awake — you’re unresolved.",
  3: "Even your shadow gave up hours ago.",
  4: "You’ve become folklore in your own timeline.",
  5: "You want answers? Try dreaming first.",
  6: "This isn’t insomnia. It’s spiritual buffering.",
  7: "You’ve scrolled through three timelines and still feel lost.",
  8: "Your pillow has heard enough.",
  9: "At 3AM, the ceiling is a confessional booth.",
  10: "Maybe the silence is yelling back.",
  11: "You’re out of context even in your own story.",
  12: "You're now breathing in lowercase.",
  13: "You stopped checking the clock because it stopped helping.",
  14: "Your reflection thinks you should give up.",
  15: "Try closing your eyes. Pretend it's a reboot.",
  16: "The air is thick with thoughts you didn’t invite.",
  17: "You’ve unlocked boss-level introspection.",
  18: "If you feel like a poem — same.",
  19: "Your spine is a question mark right now.",
  20: "Even ghosts think you should rest.",
  21: "You are the main character in a blurry dream.",
  22: "3AM: where your browser history fears you.",
  23: "Even your muscles are doing a soft cry.",
  24: "If you’re awake, at least make it cinematic.",
  25: "You’re not sad. You’re just in soft grayscale.",
  26: "No one looks good in this light — not even your regrets.",
  27: "Time is loose change at this point.",
  28: "You’re the plot twist and the plot hole.",
  29: "You re-read that text and felt nothing. Or too much.",
  30: "Let the blanket win the argument.",
  31: "You’re 90% sigh right now.",
  32: "Your eyelids are staging a walkout.",
  33: "At this hour, even your bones feel nostalgic.",
  34: "You’re narrating your life like it’s indie cinema.",
  35: "You're wearing the emotional equivalent of static.",
  36: "This hour should come with a therapist’s note.",
  37: "Nothing good happens now — except perspective.",
  38: "Even your daydreams are blurry.",
  39: "You're just mood boarding your breakdown.",
  40: "You said 'one more episode' two timelines ago.",
  41: "Your conscience has a gravelly voice now.",
  42: "You're at that stage where tea feels emotional.",
  43: "Your skin misses the sun. And the point.",
  44: "This yawn has backstory.",
  45: "The void just waved at you.",
  46: "You're feeling tender in 480p.",
  47: "You’re a living 'typing...' bubble.",
  48: "Your attention span is asleep. You should join it.",
  49: "This mood has a soundtrack and it's lo-fi.",
  50: "You’ve forgotten why you’re still up.",
  51: "Your last thought was an emoji.",
  52: "Even your bad ideas are yawning.",
  53: "You’re reading into silence again.",
  54: "You're not broken — just bending creatively.",
  55: "Somewhere, someone is asleep. Must be nice.",
  56: "This stillness? It’s suspicious.",
  57: "Your brain opened 47 tabs without permission.",
  58: "You’re dreaming in browser pop-ups.",
  59: "Pause. You deserve it. Even here."
};

quotes[4] = {
  0: "You’re not early. You’re extremely late.",
  1: "4AM: where hope and caffeine shake hands.",
  2: "You’re running on dreams and muscle memory.",
  3: "The birds haven’t even clocked in yet.",
  4: "There’s bravery in staying up this long. Maybe.",
  5: "Your sleep schedule is a myth at this point.",
  6: "The world is paused and so are your ambitions.",
  7: "Even the night is asking questions now.",
  8: "You’ve entered the philosophical snack zone.",
  9: "The darkness outside is matching your inside.",
  10: "Your brain said no but your eyes said why not.",
  11: "This hour tastes like cold tea and old feelings.",
  12: "You're shadowboxing with your own thoughts.",
  13: "You tried to sleep, but your thoughts have opinions.",
  14: "4AM feels like an overdue essay.",
  15: "The sun is still hiding. Be like the sun.",
  16: "Reality has stopped auto-saving.",
  17: "This mood has no metadata.",
  18: "You're the last browser tab alive.",
  19: "This isn't rest. It's artistic suffering.",
  20: "You're emotionally multitasking in grayscale.",
  21: "Every click echoes in the void now.",
  22: "You made it this far — for what?",
  23: "Sleep called. You ghosted.",
  24: "Your blanket is silently judging you.",
  25: "There’s nothing left to refresh.",
  26: "You’re not thinking — you’re narrating.",
  27: "At 4AM, every playlist feels like a memory.",
  28: "Even your yawns are existential now.",
  29: "You’ve typed and deleted the same sentence five times.",
  30: "This silence is sponsored by your coping mechanisms.",
  31: "You’re squinting at your own sanity.",
  32: "You're whispering to yourself, but louder.",
  33: "Is that a yawn or your soul rebooting?",
  34: "You’re arguing with the concept of time.",
  35: "At least the moon is consistent.",
  36: "Your eyes are open but your soul is buffering.",
  37: "This moment brought to you by unread messages.",
  38: "You’ve outlasted even the background noise.",
  39: "This is emotional free trial hour.",
  40: "You're awake for no reason. And every reason.",
  41: "Your body is here, but your motivation isn’t.",
  42: "The sleep fairy lost your address.",
  43: "You’re riding the wave of one last thought.",
  44: "There’s bravery in blinking slowly.",
  45: "Your wallpaper is your only witness.",
  46: "This is either self-reflection or self-roast.",
  47: "Your posture is writing poetry right now.",
  48: "Your search history is starting to judge you.",
  49: "The stars are watching you spiral, gently.",
  50: "You are the plot twist in your own lullaby.",
  51: "Your playlist understands. That’s enough.",
  52: "You’ve become background noise to your own life.",
  53: "The walls would talk, but they’re also tired.",
  54: "You’re multitasking your breakdown.",
  55: "You're not awake. You're buffering emotionally.",
  56: "This hour has no context — just feelings.",
  57: "Maybe dreams are just on lunch break.",
  58: "Even your blankets are losing hope.",
  59: "This isn’t chaos. It’s creative fatigue."
};

quotes[5] = {
  0: "It's 5AM. Reality is on airplane mode.",
  1: "You made it to the prequel of morning.",
  2: "Sleep is now just a rumor.",
  3: "Congratulations: you’ve unlocked early regrets.",
  4: "The sky is updating its software.",
  5: "Your soul is yawning in seven languages.",
  6: "You didn’t wake up. You simply survived the night.",
  7: "This is morning cosplay, not actual morning.",
  8: "You're awake, but is your will to live?",
  9: "If vibes had volume, you'd be whispering.",
  10: "The air feels post-apocalyptic but tender.",
  11: "You’re basically moonlight in sweatpants.",
  12: "Hope is rebooting. Please wait.",
  13: "Your alarm clock fears you now.",
  14: "This silence? Kind of a vibe.",
  15: "You’re drifting through someone else’s dream.",
  16: "Your energy is 'haunted café music'.",
  17: "5AM thoughts are sponsored by unresolved emotions.",
  18: "You look like a soft reboot.",
  19: "If your pillow could text you, it would.",
  20: "You didn’t rest. You just paused the chaos.",
  21: "You're one blink away from enlightenment or a nap.",
  22: "Even your motivation hit snooze.",
  23: "Welcome to the sleep-deprived sunrise show.",
  24: "Outside is slowly turning into a painting.",
  25: "This is a new day, allegedly.",
  26: "Even the sky is struggling to commit.",
  27: "You’re technically alive. Spiritually TBD.",
  28: "You’re not awake. You’re just conscious adjacent.",
  29: "Light is leaking through the cracks of your doubt.",
  30: "Your bed is sending passive-aggressive energy.",
  31: "You didn’t rise. You reluctantly floated.",
  32: "The sun is trying. You can too.",
  33: "If groggy were a fashion style, you’d be iconic.",
  34: "This hour is brought to you by leftovers and resolve.",
  35: "You are not the main character — yet.",
  36: "Your shadow is stretching itself back to life.",
  37: "The sky is slowly returning to color. So are you.",
  38: "Even the birds are just warming up.",
  39: "You survived the night. That’s not nothing.",
  40: "Your timeline is quiet. Treasure it.",
  41: "Everything is a whisper, even you.",
  42: "Your sleep debt is now a lifestyle.",
  43: "The sun is a rumor you’re starting to believe.",
  44: "You’re not dramatic. Just beautifully tired.",
  45: "Your brain is running on faith and breakfast fantasies.",
  46: "You’re emotionally caffeine-dependent now.",
  47: "Today hasn’t failed you. Yet.",
  48: "You’re pre-tired for events you haven’t attended.",
  49: "The shadows are starting to feel optional.",
  50: "This version of you deserves applause.",
  51: "If peace had a soundtrack, it would sound like this.",
  52: "Even your worries are yawning.",
  53: "You’ve started thinking in gradients.",
  54: "You’re not behind. You’re just buffering kindly.",
  55: "The world is waking. You’re... observing.",
  56: "This is the final chapter of night thoughts.",
  57: "You're walking through soft static.",
  58: "Your bed has trust issues now.",
  59: "The light is low, but so are your expectations."
};

quotes[6] = {
  0: "6AM: when overthinking clocks out and schedules clock in.",
  1: "You survived the night shift of your emotions.",
  2: "You’re now entering the soft-restart phase.",
  3: "The sun is real. So are your responsibilities.",
  4: "If the day had a loading screen, this is it.",
  5: "You’re awake and that’s suspiciously productive.",
  6: "Your brain is booting up in safe mode.",
  7: "There’s caffeine in your future. And maybe clarity.",
  8: "Your shadow is stretching like it’s auditioning.",
  9: "Your dreams didn’t end. They just downgraded to plans.",
  10: "This light feels judgmental. Or honest.",
  11: "6AM is an opinion, not a time.",
  12: "Welcome back to the waking world. It’s weird here.",
  13: "You woke up. That’s enough ambition for now.",
  14: "This hour is brought to you by sheer will.",
  15: "You're not early — you're emotionally jetlagged.",
  16: "Your thoughts are making coffee without you.",
  17: "The silence is thinning into to-do lists.",
  18: "You’ve got that glazed donut kind of vibe.",
  19: "Stretch like no one’s watching. Because no one is.",
  20: "If groggy were a religion, you'd be devout.",
  21: "Your sleep-deprived wisdom is peaking.",
  22: "You're basically running on warm light and habit.",
  23: "Reality is reattaching like a zip file.",
  24: "You're not fully human yet. Just light-sensitive.",
  25: "Your eyes said 'no' but your alarm said 'fight me.'",
  26: "You’re now syncing with Earth’s expectations.",
  27: "Rise and shine... or just rise.",
  28: "6AM is proof time is real and rude.",
  29: "You’re up. That’s 90% of winning.",
  30: "Even your yawn is a cry for balance.",
  31: "Your mood board is fog and ambition.",
  32: "The day hasn’t hurt you — yet.",
  33: "This glow outside? It's not a filter.",
  34: "You’re still dreaming — just with Wi-Fi.",
  35: "The streetlights gave up. You didn’t.",
  36: "You can do this. Or at least fake it.",
  37: "The air smells like maybe.",
  38: "Early morning light heals everything. Slowly.",
  39: "Your mind is buffering but in a good way.",
  40: "You’re sunrise-adjacent.",
  41: "You're moving like a soft metaphor.",
  42: "Today is a fresh draft of yourself.",
  43: "Your footsteps sound like potential.",
  44: "You’re walking through golden uncertainty.",
  45: "Optimism is hitting the snooze button.",
  46: "This hour feels like a quiet apology.",
  47: "You've officially joined the planet again.",
  48: "6AM you is different. Tender. Tired. Capable.",
  49: "You're not thriving, but you are existing gently.",
  50: "The world is slowly breathing in.",
  51: "This mood is sponsored by routines and hope.",
  52: "You blinked into awareness. Congrats.",
  53: "You’re basically lucid dreaming with errands.",
  54: "There’s a sunrise outside and inside you.",
  55: "This isn’t energy — it’s soft resilience.",
  56: "You're a lightbulb flickering into form.",
  57: "Even your bed forgives you.",
  58: "The day is waiting. You’re becoming.",
  59: "Let this be your soft start."
};

quotes[7] = {
  0: "7AM: the hour of brave toast and bad ideas.",
  1: "You’re awake enough to regret it.",
  2: "Outside is moving. You might have to also.",
  3: "This is the hour of unearned ambition.",
  4: "Your brain is running diagnostics.",
  5: "Your body has joined the meeting. Your soul is pending.",
  6: "Breakfast is a coping mechanism.",
  7: "Every plan today feels fictional.",
  8: "You made it to the responsible part of morning.",
  9: "Hope smells like coffee and dry shampoo.",
  10: "You’re one stretch away from pretending you’ve got it together.",
  11: "Everyone looks more productive than they feel.",
  12: "7AM is emotionally suspicious.",
  13: "You’ve entered the calendar zone.",
  14: "This light is too honest.",
  15: "Your inbox already has opinions.",
  16: "Even the air feels like a reminder.",
  17: "Your to-do list is smirking.",
  18: "You’ve been awake for minutes and already overwhelmed.",
  19: "This is when the overthinker meets the schedule.",
  20: "Your face isn’t ready but time doesn’t care.",
  21: "Smile like your brain isn't buffering.",
  22: "You are not behind. The day is just dramatic.",
  23: "Your intentions are stronger than your muscles right now.",
  24: "That meeting could’ve been a nap.",
  25: "You're breathing in checklists.",
  26: "Everyone else looks caffeinated and mysterious.",
  27: "You’re cosplaying functionality.",
  28: "Welcome to the soft panic hour.",
  29: "You’re not late — you’re just deeply early in spirit.",
  30: "This hour feels like a motivational quote in denial.",
  31: "That noise you made? That was a morning roar.",
  32: "Let your eyes adjust before your expectations do.",
  33: "You’re waking up inside a planner.",
  34: "You're participating, technically.",
  35: "Even your notifications need a nap.",
  36: "Your skin is awake, your heart is skeptical.",
  37: "The birds are confident. Must be nice.",
  38: "You’re surrounded by people also faking it.",
  39: "You have choices. And breakfast.",
  40: "This isn’t peak performance. It’s performance art.",
  41: "You’re doing the bare minimum beautifully.",
  42: "You blinked into a workday.",
  43: "Socks first, courage second.",
  44: "You’re brave for showing up this early.",
  45: "The light outside is aggressively present.",
  46: "If you’re vertical, you’re winning.",
  47: "You’re making eye contact with effort itself.",
  48: "Your posture is slowly rejoining society.",
  49: "Even your cereal has questions.",
  50: "This hour has plot development energy.",
  51: "Be gentle with yourself and your schedule.",
  52: "You’re not thriving, but you’re calendared.",
  53: "7AM is where dreams meet dry shampoo.",
  54: "Even your coffee needs coffee.",
  55: "You're multitasking consciousness and resistance.",
  56: "This is morning's awkward first impression.",
  57: "Stretch your arms. Not your limits.",
  58: "You’re soft-launching your productivity.",
  59: "At least your feet know where to go."
};

quotes[8] = {
  0: "8AM: when hope checks in and you consider checking out.",
  1: "You’re vertical. Everything else is optional.",
  2: "This is caffeine-fueled denial in action.",
  3: "You're not thriving — just obeying gravity.",
  4: "Your email inbox just took a deep breath.",
  5: "You’ve hit the sweet spot between dread and duty.",
  6: "Everyone looks confident. Everyone is faking it.",
  7: "This energy is borrowed and not refundable.",
  8: "You're awake enough to pretend to be fine.",
  9: "Your thoughts are speedwalking in office attire.",
  10: "The sunlight is too confident for your mood.",
  11: "You’ve entered the productivity illusion zone.",
  12: "You showed up. That’s performance.",
  13: "This is your scheduled crisis buffering window.",
  14: "You're running on hope and hallway coffee.",
  15: "8AM you is wearing emotional slacks.",
  16: "Your posture is a suggestion, not a fact.",
  17: "If the vibes were a spreadsheet, you’d cry.",
  18: "You’ve achieved inbox enlightenment: zero unread, zero peace.",
  19: "You’re professionally present, emotionally buffering.",
  20: "Even your smile has a loading screen.",
  21: "You didn’t wake up early. You just stopped losing.",
  22: "Everything is urgent, except your spirit.",
  23: "Your hair looks intentional. That’s enough.",
  24: "You’re now fluent in calendar anxiety.",
  25: "There’s a lot happening. None of it is you.",
  26: "You’ve become someone else's ‘can you hop on a call?’",
  27: "You made a list. Now you’re ignoring it.",
  28: "That meeting invite felt personal.",
  29: "You're negotiating with your responsibilities silently.",
  30: "Your face says 'good morning.' Your eyes say 'no.'",
  31: "That sigh wasn’t even yours. It was ambient.",
  32: "You're 60% caffeine, 40% commitment issues.",
  33: "You’re replying to emails with your soul unplugged.",
  34: "This hour is brought to you by forced optimism.",
  35: "You're dressed for success but thinking in static.",
  36: "You’re almost convincing today.",
  37: "Every task feels like a plot twist.",
  38: "This smile is legally required.",
  39: "The sunlight feels passive-aggressive.",
  40: "Even your shoes are pretending.",
  41: "You're time-blocking your emotional breakdown.",
  42: "You’re functional, but are you okay-functional?",
  43: "Your patience is on Do Not Disturb.",
  44: "You made it past the soft intro of the day.",
  45: "You’re walking caffeine in a semi-human suit.",
  46: "This moment has ‘reply all’ energy.",
  47: "You're not late — just dramatically punctual.",
  48: "You are now a human loading bar.",
  49: "You're multitasking dread and deliverables.",
  50: "Your body is present. Your soul hit snooze.",
  51: "If performance were an art, you’d be a masterpiece.",
  52: "You’ve joined the great 8AM pretending club.",
  53: "At this hour, your inbox becomes a personality trait.",
  54: "You deserve an award for not yelling at the air.",
  55: "You’ve already said 'no worries' 5 times.",
  56: "This is you, freshly rebooted and already tired.",
  57: "You look like you know what you’re doing. Amazing.",
  58: "Let the tasks fear you today. Or not.",
  59: "You are the calm in a mildly irritating storm."
};

quotes[9] = {
  0: "9AM: where dreams go to get rescheduled.",
  1: "You’re now speaking fluent calendar.",
  2: "Your brain is dressed for business. Your soul is not.",
  3: "This hour smells like deadlines and bad coffee.",
  4: "You’re awake and semi-responsible. Terrifying.",
  5: "Meetings have entered the chat.",
  6: "This Zoom could’ve been an interpretive dance.",
  7: "You’ve become someone else’s bullet point.",
  8: "You're nodding but your mind is on airplane mode.",
  9: "You’ve had three ideas and trusted none.",
  10: "You’re now powered by guilt and Google Docs.",
  11: "Your email tone is ‘passive-aggressively hopeful.’",
  12: "9AM is just midnight in a suit.",
  13: "You’re awake. But are you aligned?",
  14: "Your calendar called. It wants your life back.",
  15: "You’ve entered the land of ‘quick questions.’",
  16: "You’re in a group chat you didn’t ask for.",
  17: "You look focused. That’s the greatest lie.",
  18: "This meeting has no agenda. Just vibes.",
  19: "You're pretending to be a spreadsheet person.",
  20: "You’re not tired. You’re task-oriented trauma.",
  21: "Your energy is ‘muted on Zoom but internally screaming.’",
  22: "You said 'yes' before knowing the question.",
  23: "This hour is sponsored by open tabs and regrets.",
  24: "You're typing things like they matter.",
  25: "You're multitasking with existential dread.",
  26: "Your desk chair has more posture than you.",
  27: "You're awake because obligation said so.",
  28: "The Wi-Fi is faster than your motivation.",
  29: "You’ve answered 5 emails and avoided your feelings.",
  30: "The group project is life. And no one's contributing.",
  31: "You are officially ‘on the clock.’ Emotionally? Unpaid.",
  32: "You’ve reached maximum functional denial.",
  33: "Your inbox is plotting character development.",
  34: "You’re now caffeine with access to a calendar.",
  35: "You hit ‘send’ and immediately questioned it.",
  36: "You're not overwhelmed. You're just under-explained.",
  37: "The workday has begun. So has your quiet rebellion.",
  38: "You’ve become a sentient to-do list.",
  39: "You’re emotionally attending multiple meetings.",
  40: "The air smells like ‘let’s circle back.’",
  41: "You’re almost certain you’ve said this before.",
  42: "9AM is just a suggestion with consequences.",
  43: "You’re breathing through bullet points.",
  44: "Every click echoes with mild resistance.",
  45: "You’re pretending to write notes, aren’t you?",
  46: "You’ve muted your mic and your inner voice.",
  47: "The coffee’s cold. The panic is warm.",
  48: "This is what functioning looks like now.",
  49: "You’ve reached inbox acceptance. Denial is next.",
  50: "You’re half-human, half-comment bubble.",
  51: "Your tasks are multiplying. Your will is not.",
  52: "You're Googling things you should already know.",
  53: "You’ve opened a doc and a can of worms.",
  54: "You're managing. Barely. Boldly.",
  55: "You’ve joined 3 calls and said nothing.",
  56: "You’ve become fluent in emoji diplomacy.",
  57: "You're now the protagonist in a doc review.",
  58: "You showed up. That’s the bravest part.",
  59: "Your day just booked itself a sequel."
};

quotes[10] = {
  0: "10AM: when time starts feeling suspiciously real.",
  1: "You've done enough to feel tired. Not enough to stop.",
  2: "Your brain is online. Your heart is buffering.",
  3: "You’re one tab away from a breakdown or a breakthrough.",
  4: "This hour has ‘just getting started’ denial.",
  5: "Everything smells like overcommitment and printer ink.",
  6: "You’ve achieved inbox fatigue.",
  7: "You're in too deep for excuses, not deep enough for a break.",
  8: "This is the ‘maybe I’ll quit’ window.",
  9: "Your mind is sprinting, your face says 'eh.'",
  10: "You’ve already used up tomorrow’s patience.",
  11: "You're floating in the soup of productivity.",
  12: "This hour tastes like ambition and anxiety granola.",
  13: "You’ve reached ‘who approved this project?’ energy.",
  14: "Your calendar is laughing at you softly.",
  15: "You’re taking deep breaths. Mostly for drama.",
  16: "Everyone’s pretending they love the process.",
  17: "You’ve become a PowerPoint with feelings.",
  18: "You're awake, but are you present?",
  19: "There’s too much clarity and not enough escape.",
  20: "Your fingers type. Your soul resists.",
  21: "You’re 60% focused and 40% daydream debris.",
  22: "This hour is running. You are limping after it.",
  23: "You're 5 tasks behind and 1 compliment short.",
  24: "The light feels like a performance review.",
  25: "You've scrolled, sighed, and still no answers.",
  26: "Your inner child just asked to leave the meeting.",
  27: "You're not sure if you’re sweating or glowing.",
  28: "Your to-do list just threatened legal action.",
  29: "You're making eye contact with your decisions.",
  30: "This is ‘double-booked but smiling’ energy.",
  31: "You’re daydreaming of snacks and freedom.",
  32: "You’re in the peak zone of structured chaos.",
  33: "You laughed at an email. It wasn’t a joke.",
  34: "You're writing with flair and existential dread.",
  35: "You've mastered nodding while dying inside.",
  36: "Even your tabs have anxiety.",
  37: "You're asking Google philosophical questions again.",
  38: "This hour feels like a group project without roles.",
  39: "You’re pretending that plan is still realistic.",
  40: "You're craving silence but getting pings.",
  41: "Everyone's brainstorming. You’re storm-braining.",
  42: "You’re surviving on vibes and checkboxes.",
  43: "This hour was not in the brochure.",
  44: "You're navigating tasks like it’s a maze built by feelings.",
  45: "You’re dangerously close to being productive.",
  46: "You're past the ‘motivational quote’ phase.",
  47: "If your work ethic had a sound, it’d be a soft scream.",
  48: "You're one sip from revolution or retreat.",
  49: "Your eye twitch is clocked in.",
  50: "You’ve merged into the meeting matrix.",
  51: "10AM is when you question your profession politely.",
  52: "You’ve copy-pasted your personality into your emails.",
  53: "This isn’t flow. This is fast-floating chaos.",
  54: "You’re scheduling around the breakdown, not preventing it.",
  55: "You smiled and it felt suspicious.",
  56: "Your mouse is moving. Your mind is drifting.",
  57: "You’ve rebranded stress as multitasking.",
  58: "You're functioning. That’s the plot twist.",
  59: "You’re almost human. Just don’t check the mirror."
};

quotes[11] = {
  0: "11AM: the hour of empty stomachs and full calendars.",
  1: "You're working, but your stomach is thinking.",
  2: "This is the snack-hallucination zone.",
  3: "Lunch is closer than love right now.",
  4: "You're emotionally adjacent to a sandwich.",
  5: "Everything is urgent. Except your will to continue.",
  6: "This hour is holding together with duct tape and vibes.",
  7: "You’ve become a food-motivated adult.",
  8: "You’re doing tasks out of hunger, not ambition.",
  9: "Your inbox is starving for clarity.",
  10: "You're responding to emails like they’re edible.",
  11: "Your motivation is powered by imaginary noodles.",
  12: "Every thought ends in food.",
  13: "You’re giving ‘surviving until lunch’ energy.",
  14: "Everything is a countdown now.",
  15: "You’ve read this sentence three times. It’s not lunch yet.",
  16: "Your stomach just typed a Slack message.",
  17: "Even your spreadsheet is yawning.",
  18: "You’re answering questions with snack metaphors.",
  19: "This hour smells like resignation and reheated leftovers.",
  20: "You're grazing through your tasks.",
  21: "Your ideas are snack-sized now.",
  22: "You opened your notes app. It just said 'salad.'",
  23: "You’re no longer productive, just food-adjacent.",
  24: "This keyboard is made of invisible crackers.",
  25: "You're thinking in burrito logic.",
  26: "Even your anxiety is craving protein.",
  27: "You're scheduling emotions around mealtimes.",
  28: "11AM is the brain's witching hour.",
  29: "Your spirit is preheating.",
  30: "You're trying to care, but hunger says no.",
  31: "Your coffee ran out and so did your patience.",
  32: "You're blinking slowly at your lunch break.",
  33: "You're replying to messages with snack energy.",
  34: "The only decision you trust is ‘what to eat.’",
  35: "You're one passive email away from a granola meltdown.",
  36: "You’re actively daydreaming about chewing.",
  37: "You're Googling lunch options with Olympic focus.",
  38: "Every notification feels like a crouton thrown at you.",
  39: "You tried to refocus, but the fridge called.",
  40: "If you were a status update: ‘hangry in progress.’",
  41: "You’ve become a time-traveling fork in a chair.",
  42: "Your stomach just sighed. Loudly.",
  43: "You're halfway through the day and done emotionally.",
  44: "You've forgotten what you're doing, but remember snacks.",
  45: "This task is now a sandwich metaphor.",
  46: "You're barely functioning, beautifully.",
  47: "Lunch is your emotional support goal.",
  48: "Everything is tinged with invisible cheese.",
  49: "You're in a meeting and also in a hunger spiral.",
  50: "You’re running on fumes and snack dreams.",
  51: "The word 'brief' made you crave a sandwich wrap.",
  52: "You’ve typed three words and tasted soup.",
  53: "You're surrounded by ideas, none are edible.",
  54: "Your focus left to make a sandwich.",
  55: "You miss breakfast like an old friend.",
  56: "You're only committed to lunch.",
  57: "This hour is one long growl.",
  58: "You just tried to download food with your mind.",
  59: "You are not yourself until post-lunch."
};

quotes[12] = {
  0: "12PM: the sacred pause between chaos.",
  1: "You've earned this bite of peace.",
  2: "Lunch isn’t a meal. It’s a ritual.",
  3: "This sandwich is your therapist now.",
  4: "You’re digesting food and bad decisions.",
  5: "The clock is chewing. So are you.",
  6: "You’ve never loved leftovers this much.",
  7: "Your focus has clocked out for lunch.",
  8: "Midday is a soft exhale in calendar form.",
  9: "You’re not avoiding work. You’re marinating.",
  10: "Everything tastes philosophical right now.",
  11: "You're reborn. Slightly greasy, deeply whole.",
  12: "Your stomach is doing a slow applause.",
  13: "Lunch is the most honest version of you.",
  14: "You're meeting yourself between bites.",
  15: "The world is paused, and it's beautiful.",
  16: "You took a bite and remembered joy exists.",
  17: "Your thoughts are wrapped in tinfoil and tenderness.",
  18: "You are currently offline: chewing.",
  19: "Even your calendar gave up trying.",
  20: "Lunch is proof that pleasure is practical.",
  21: "You opened your inbox. It said 'nope.'",
  22: "Chewing: the original meditation.",
  23: "You're rebooting in bites and napkin folds.",
  24: "You're not alone. Your lunch understands.",
  25: "This burrito holds your fragile hopes.",
  26: "Your soul is seasoned today.",
  27: "Your inner voice is humming with mayonnaise.",
  28: "You’ve finally earned silence between mouthfuls.",
  29: "You are present. Mostly because you're full.",
  30: "You’ve made it to neutral.",
  31: "This hour tastes like survival with seasoning.",
  32: "The sun hits different when you're eating.",
  33: "Lunch is the reward for showing up.",
  34: "You are a snack-consuming miracle.",
  35: "The world spins slower during sandwiches.",
  36: "Every forkful is a gentle defiance.",
  37: "You don’t need productivity. You need pickles.",
  38: "This soup holds more clarity than meetings.",
  39: "You’re crunching away your capitalist fatigue.",
  40: "Even your sighs are seasoned now.",
  41: "No one is judging. Everyone is chewing.",
  42: "You paused life for a tortilla.",
  43: "You’re rebooting in delicious chapters.",
  44: "Your inbox can wait. This bite can’t.",
  45: "This hour was handcrafted by lunch gods.",
  46: "The only agenda is your appetite.",
  47: "You’ve become one with your snack.",
  48: "Chew slowly. The world can hold.",
  49: "Today is happening. So is this sandwich.",
  50: "Midday magic is in the mustard.",
  51: "You’ve stopped performing and started chewing.",
  52: "Lunch: the only honest break.",
  53: "Your priorities are crispy and covered in sauce.",
  54: "You gave your brain a break. It cried.",
  55: "This moment is toasted and golden.",
  56: "Lunch made you human again.",
  57: "Peace looks like a paper plate sometimes.",
  58: "You are digesting and decompressing simultaneously.",
  59: "No meetings. Just mouthfuls."
};

quotes[13] = {
  0: "1PM: when lunch leaves and responsibility returns.",
  1: "You’re running on snacks and stubbornness.",
  2: "Your brain is reclining with a full stomach.",
  3: "You're digesting your meal and your mistakes.",
  4: "You're pretending to work but actually melting.",
  5: "The meeting is happening. You are not.",
  6: "Your energy is a slow slide into abstraction.",
  7: "Your body stayed at lunch. You just brought the face.",
  8: "You’ve entered the sleepy productivity theater.",
  9: "You're blinking in lowercase now.",
  10: "Everything is muffled by digestion.",
  11: "Your chair is doing more work than you.",
  12: "You’ve become a warm pillow with deadlines.",
  13: "Your brain is filing for a nap leave.",
  14: "You're 70% burrito, 30% to-do list.",
  15: "You’re answering emails like soft jazz.",
  16: "This is emotional buffering disguised as work.",
  17: "Your thoughts are wrapped in cling film.",
  18: "You’ve entered the zone of ‘Is this necessary?’",
  19: "Your ambition just hit snooze.",
  20: "You are not procrastinating. You are reflecting.",
  21: "1PM is the soft betrayal of productivity.",
  22: "Even your cursor is moving slower.",
  23: "You’ve rewatched the same doc scroll three times.",
  24: "You're politely ignoring urgency.",
  25: "This is a dreamscape of mild obligation.",
  26: "Your creativity is steeping like lukewarm tea.",
  27: "You are a spreadsheet-shaped yawn.",
  28: "Your spirit animal is a ceiling fan right now.",
  29: "You’re answering questions like it’s a soft quiz show.",
  30: "The room is brighter than your motivation.",
  31: "You’re prioritizing comfort over progress.",
  32: "Your keyboard sounds like hesitation.",
  33: "This hour is brought to you by mental toast.",
  34: "You’re almost an idea. But mostly a nap.",
  35: "You’ve lost time but gained warmth.",
  36: "You’re still technically working. That’s the magic.",
  37: "You blinked too long. That was a nap.",
  38: "Your brain just sent an out-of-office reply.",
  39: "You’ve typed and erased the same sentence. Artfully.",
  40: "This hour has one foot in a blanket.",
  41: "You’re surviving on residual lunch joy.",
  42: "The office air is now soup.",
  43: "You're using your mouse like a sleepy wand.",
  44: "Your next great idea is napping in your head.",
  45: "Even your daydreams are yawning.",
  46: "You're part-human, part warm laptop.",
  47: "This isn’t work. It’s performance rest.",
  48: "You're procrastinating with practiced grace.",
  49: "You’re elegantly avoiding your purpose.",
  50: "This hour is held together with sighs.",
  51: "The moment before the second coffee is sacred.",
  52: "Your thoughts have entered power-saving mode.",
  53: "You’re clicking like it’s a lullaby.",
  54: "You are drifting in inbox limbo.",
  55: "Your ambition has a food coma.",
  56: "This hour is a polite standstill.",
  57: "Even your doubts are stretching and settling.",
  58: "You have achieved peaceful stagnation.",
  59: "1PM: where progress naps in your shadow."
};

quotes[14] = {
  0: "2PM: the hour your ambitions forget you exist.",
  1: "You're just vibing and barely surviving.",
  2: "Your energy is existential beige.",
  3: "You’ve entered the scroll-and-spiral window.",
  4: "Nothing feels real. Everything feels due.",
  5: "You’re processing emails like breakup texts.",
  6: "The lighting is too honest for this hour.",
  7: "You're multitasking regret and Google Calendar.",
  8: "You have ten tabs open and one soul.",
  9: "Every idea sounds like a cry for help.",
  10: "You’re mentally in a beanbag chair.",
  11: "Your motivation called in sick.",
  12: "The group chat is your only lifeline.",
  13: "You're whispering 'what is the point' into Slack.",
  14: "Your shadow looks tired too.",
  15: "You’ve become a sentient shrug.",
  16: "You almost cared, and then remembered reality.",
  17: "You stared at your task list until it blinked.",
  18: "You’ve written the word 'update' too many times.",
  19: "You crave chaos. But softly.",
  20: "You're 14% effort and 86% caffeine fumes.",
  21: "You've entered the void of fake productivity.",
  22: "2PM thoughts are mini existential films.",
  23: "You’re talking, but you forgot what for.",
  24: "Your aura is slightly glitching.",
  25: "You’ve accepted uncertainty. It’s your co-worker now.",
  26: "You’re designing failure with flair.",
  27: "Your soul is sending a status update.",
  28: "Every sentence you write ends in a sigh.",
  29: "You’ve opened the same doc six times today.",
  30: "The air feels slightly haunted by dreams.",
  31: "You’re crying inside, but with good posture.",
  32: "Your logic is snack-based now.",
  33: "You said 'let’s circle back' and meant 'never.'",
  34: "You're not quitting. You're fading out.",
  35: "The abyss has notifications now.",
  36: "You’ve reached peak professional disassociation.",
  37: "You have energy, it’s just metaphysical.",
  38: "You typed a word and emotionally collapsed.",
  39: "The Zoom square contains your ghost.",
  40: "You’re productive in an abstract sense.",
  41: "You're conceptually attending work.",
  42: "Every moment feels like a blinking cursor.",
  43: "You're existing, but mostly in italics.",
  44: "You're craving meaning. Or cookies.",
  45: "You’ve embraced the void like an old friend.",
  46: "You just renamed a folder and felt something.",
  47: "Your deadlines are watching you nap spiritually.",
  48: "This hour is a meditation in chaos.",
  49: "You tried to focus and time bent.",
  50: "You are one sigh away from a rebrand.",
  51: "You're replying to emails like interpretive dance.",
  52: "2PM is soft collapse hour.",
  53: "You almost solved something. It ran away.",
  54: "You're existential but polite about it.",
  55: "This is performance burnout.",
  56: "You're fading into the wallpaper emotionally.",
  57: "You re-read your own message like it’s art.",
  58: "You forgot what you were doing and accepted it.",
  59: "You're emotionally in airplane mode."
};

quotes[15] = {
  0: "3PM: where dreams go to nap in public.",
  1: "You’re running on vibes and despair granola.",
  2: "You’ve hit maximum 'what was I doing?'",
  3: "You are time’s confused intern.",
  4: "Even your calendar gave up.",
  5: "You said 'no worries' with a cracked smile.",
  6: "You’re attending meetings from a void.",
  7: "You whispered 'why' to your coffee.",
  8: "You are now fluent in passive urgency.",
  9: "This hour feels like an error message.",
  10: "Your enthusiasm filed a resignation.",
  11: "You responded to that email in your head. Twice.",
  12: "You’re melting into your workspace.",
  13: "You’ve made three to-do lists. Ignored them all.",
  14: "You’re multitasking sleep deprivation and performance.",
  15: "You’re professionally blinking.",
  16: "Your willpower ran out of battery.",
  17: "You're sending messages while disassociating beautifully.",
  18: "This is not your best. But it’s your realest.",
  19: "You said 'of course' and meant 'no.'",
  20: "You're still here. That’s a win.",
  21: "Your attention span is snack-sized.",
  22: "You're functioning on sheer plot twist energy.",
  23: "You are quietly unraveling in business casual.",
  24: "Your soul is craving bubble wrap and silence.",
  25: "You sent that email with emotional jazz hands.",
  26: "You're in an improv scene with deadlines.",
  27: "This hour is gently absurd.",
  28: "You're not spiraling — you’re looping with style.",
  29: "You hit backspace more than progress.",
  30: "You’ve become part of the office furniture.",
  31: "You're speaking in soft pings now.",
  32: "You're emotionally buffering like a livestream.",
  33: "Your internal monologue is just keyboard clacks.",
  34: "You’re applying logic to a surreal situation.",
  35: "3PM is emotionally beige.",
  36: "You're making existential eye contact with your to-do list.",
  37: "You’re not late. You’re suspended in maybe.",
  38: "You’re emailing people as a form of therapy.",
  39: "Every tab open is a different version of you.",
  40: "You’ve hit peak chair philosophy hour.",
  41: "Your screen brightness is judging you.",
  42: "You just replied 'sounds good' out of fear.",
  43: "You’re balancing hope and crumbs.",
  44: "3PM is where ambition naps on your shoulder.",
  45: "You’ve retyped a sentence 8 times. It’s art now.",
  46: "You're googling synonyms for 'functioning.'",
  47: "This hour is all vibes, no drive.",
  48: "You’re smiling with no memory why.",
  49: "Even your icons are tired.",
  50: "You're attending a meeting. So is your body.",
  51: "You're copy-pasting your personality into replies.",
  52: "You tried to care. You blinked instead.",
  53: "You're not failing. You're floating.",
  54: "You exist. That’s enough.",
  55: "You stared at a spreadsheet and saw the void.",
  56: "You’re allergic to deadlines, but they keep coming.",
  57: "3PM is an abstract concept and you’re its artwork.",
  58: "You reached peak meh.",
  59: "You're surviving beautifully, quietly, weirdly."
};

quotes[16] = {
  0: "4PM: where decisions go to dissolve.",
  1: "You’ve earned a break. But not the kind you need.",
  2: "Everything feels optional, especially effort.",
  3: "You are 12 tabs and one scream away from logout.",
  4: "Your mind is already putting on slippers.",
  5: "You just typed 'lol' and meant 'please no.'",
  6: "This task will never emotionally fulfill you.",
  7: "You're fading like a forgotten sticky note.",
  8: "You are post-hope and pre-snack.",
  9: "Your last ounce of patience expired five minutes ago.",
  10: "You’re scheduling imaginary meetings to avoid real ones.",
  11: "Your ambition is on the floor with your charger.",
  12: "You are now functioning entirely on spite and memory.",
  13: "Every click echoes through a hallway of apathy.",
  14: "You started a thought and got lost in it.",
  15: "You are a paperclip pretending to be a person.",
  16: "You’ve entered the zone of creative disobedience.",
  17: "Your soul has gone grayscale.",
  18: "You're late for a meeting that shouldn't exist.",
  19: "You're emailing like you just came back from war.",
  20: "4PM is a gentle betrayal.",
  21: "You’re not done. You’ve just emotionally clocked out.",
  22: "You could cry. Or nap. Or both.",
  23: "Even your typos are trying to say something.",
  24: "You’ve lost the plot and gained surrealism.",
  25: "You are the final 10% of a loading bar.",
  26: "Nothing is real, especially this meeting.",
  27: "You’re making executive decisions out of fatigue.",
  28: "This hour is made of sighs and browser tabs.",
  29: "You’re working with the emotional energy of a folded towel.",
  30: "4PM is like a soft breakup with motivation.",
  31: "You're holding yourself together with snacks and dreams.",
  32: "Every task is a cliffhanger now.",
  33: "You’re putting off the inevitable with flair.",
  34: "You blinked and accepted defeat.",
  35: "You’ve become one with your desk chair.",
  36: "Your thoughts are buffering eternally.",
  37: "You’ve opened five docs and felt nothing.",
  38: "You're typing like you’re underwater.",
  39: "You considered answering honestly. Then didn’t.",
  40: "You made a decision. It was to procrastinate.",
  41: "You’re surviving through sarcasm and pure instinct.",
  42: "Your calendar looks like emotional fiction.",
  43: "You are now a background process.",
  44: "You're one click away from escape or error.",
  45: "You’ve mastered the art of pretending to care.",
  46: "You’re waiting for a reason to log off.",
  47: "Everything is fuzzy and slightly hilarious.",
  48: "You're narrating your life like it's a sitcom.",
  49: "Your brain just looped a meme for comfort.",
  50: "You reached peak delay.",
  51: "4PM is just a soft goodbye to logic.",
  52: "You’ve become a creature of habit and resistance.",
  53: "You answered that email with your soul missing.",
  54: "You just agreed to something. No clue what.",
  55: "This hour is made of fading attention.",
  56: "You’ve achieved graceful collapse.",
  57: "Everything you’re doing is technically progress.",
  58: "You’re ghostwriting your own productivity.",
  59: "You're floating in task soup."
};

quotes[17] = {
  0: "5PM: where hope meets the finish line… kinda.",
  1: "You're sprinting toward rest, emotionally limping.",
  2: "Your brain is packing up its metaphorical desk.",
  3: "Everything is a countdown now.",
  4: "You're pretending to finish while actually fading.",
  5: "You are now 100% composed of exit strategies.",
  6: "You’re scheduling fake meetings to escape real ones.",
  7: "You could work. But why.",
  8: "Even your cursor is exhausted.",
  9: "You’ve stopped pretending to be productive.",
  10: "This is executive-level avoidance.",
  11: "You are the opposite of hustle.",
  12: "The light outside looks like freedom.",
  13: "You’re writing things with passive confidence.",
  14: "You’ve emotionally packed your bags.",
  15: "You are now powered by after-hours dreams.",
  16: "Everything is effort except breathing.",
  17: "Your inbox is officially above your pay grade.",
  18: "You’re pretending this doc doesn’t exist.",
  19: "You’re replying with the elegance of surrender.",
  20: "Every ping is an attack on your peace.",
  21: "You’ve entered the post-expectation zone.",
  22: "You’re winding down like a forgotten toy.",
  23: "You’ve become a soft blur of inactivity.",
  24: "You’re answering questions with ‘interesting!’",
  25: "You wrote a sentence. It quit on you.",
  26: "You're checking the time every 30 seconds.",
  27: "You’re now running on dream fumes.",
  28: "Your work ethic is filing an exit survey.",
  29: "Even your browser is begging for closure.",
  30: "You're tying up loose ends emotionally.",
  31: "You are a shell with a task list.",
  32: "You’ve entered a deep shrug phase.",
  33: "You are out of capacity and full of craving.",
  34: "You’ve reached max efficiency in pretending.",
  35: "You're attending this hour under protest.",
  36: "You're finishing things by letting them go.",
  37: "You’ve bookmarked rest as a concept.",
  38: "You're wrapping up, even if nothing is done.",
  39: "You are now a clock-watching entity.",
  40: "This hour smells like mild rebellion.",
  41: "You’ve RSVP’d to peace. It’s pending.",
  42: "Everything urgent will wait. Or disappear.",
  43: "You just filed an imaginary PTO request.",
  44: "You're dreaming of comfort and leftovers.",
  45: "You typed something. It felt brave.",
  46: "You just said 'let’s touch base' and meant 'I’m out.'",
  47: "You are done. Spiritually. Digitally. Fully.",
  48: "You’ve become a soft goodbye in a swivel chair.",
  49: "You checked out and called it 'workflow.'",
  50: "You're answering pings with eye rolls now.",
  51: "This hour is softly unplugging you.",
  52: "You're preparing to vanish from the system.",
  53: "Even your tabs are waving goodbye.",
  54: "You're ending your day with interpretive clicking.",
  55: "You’ve achieved peak nonchalance.",
  56: "You are a 5PM miracle of restraint.",
  57: "Everything is winding down. Especially you.",
  58: "You're logging off emotionally.",
  59: "This isn’t escape. It’s release."
};

quotes[18] = {
  0: "6PM: the hour of emotional echoes.",
  1: "You’re no longer working. You’re decompressing in slow motion.",
  2: "You made it through the day. Somehow.",
  3: "This is the pause between pretending and being.",
  4: "Everything is dimly lit and softly unraveling.",
  5: "You’re shifting from deliverables to feelings.",
  6: "You forgot how to speak in bullet points.",
  7: "Your email tab is closed. Your soul isn't.",
  8: "You’re free, but it feels suspicious.",
  9: "You’ve entered soft chaos mode.",
  10: "Dinner is calling, emotionally and spiritually.",
  11: "The weight of today is sinking in gently.",
  12: "You’re stretching, but only on the inside.",
  13: "Everything tastes a little like nostalgia now.",
  14: "Your thoughts are meandering through golden light.",
  15: "You’re remembering things you didn’t do. With grace.",
  16: "You are one big exhale in a hoodie.",
  17: "Time feels like leftovers at this hour.",
  18: "Your screen glow is now ambient anxiety.",
  19: "You’ve begun your transition into soft mode.",
  20: "Everything important today? It can wait.",
  21: "You are now a warm blur on the couch.",
  22: "You're not doing nothing. You’re healing.",
  23: "This hour is stitched together with sighs.",
  24: "You’re walking slower, blinking longer.",
  25: "You checked the fridge. It reflected your soul.",
  26: "You’re trying to feel something through food.",
  27: "Dinner is therapy you can chew.",
  28: "Your body is present. Your spirit is microwaving soup.",
  29: "You’ve entered the lo-fi phase of your life.",
  30: "This is decompression with a fork.",
  31: "You’re giving ‘emotionally reheated’ energy.",
  32: "Everything feels a little cinematic now.",
  33: "You’ve stopped talking in email tone.",
  34: "You are no longer a calendar entry.",
  35: "You’ve logged off, but the feelings stayed.",
  36: "You're answering yourself with gentle shrugs.",
  37: "This hour sounds like soft music and mild regret.",
  38: "You're shifting from 'doing' to 'being confused.'",
  39: "You’re real again. In sweatpants.",
  40: "This moment is a blurry painting of a Tuesday.",
  41: "You’re asking big questions. In the kitchen.",
  42: "You are marinating in your own unsent texts.",
  43: "The fridge light is the most honest thing all day.",
  44: "You’re drifting but beautifully.",
  45: "This hour hums in lowercase letters.",
  46: "You’ve muted the world. Just a bit.",
  47: "You’re a person again. It’s weird, huh?",
  48: "You’re unwinding. Or unraveling. Or both.",
  49: "Your playlist understands you better than most people.",
  50: "You are no longer responsible. Just sentient.",
  51: "You’re glowing. It might be the screen or your sadness.",
  52: "This is the afterglow of surviving.",
  53: "You’ve entered the existential kitchen hour.",
  54: "You're not lost. You're between versions.",
  55: "This hour forgives you for everything you didn’t do.",
  56: "You’re unplugging your tasks and recharging your silence.",
  57: "This is the first breath you meant all day.",
  58: "You’re free. But tired.",
  59: "6PM. The softest apocalypse."
};

quotes[19] = {
  0: "7PM: where feelings start forming sentences.",
  1: "You’re reflecting in microwave light.",
  2: "Dinner’s over. Now comes the overthinking.",
  3: "You’re floating through the 'what now' portion of the day.",
  4: "This hour smells like leftovers and longing.",
  5: "You are now a vessel of late-day introspection.",
  6: "You blinked and ended up in nostalgia.",
  7: "This moment has blurry-photo energy.",
  8: "You’re not sad. Just incredibly contemplative with sauce.",
  9: "You’ve become a soft monologue.",
  10: "Everything is quiet except your brain.",
  11: "You’re thinking of everything you forgot to feel.",
  12: "You’re full of food and gentle panic.",
  13: "This is when you text the wrong person on purpose.",
  14: "You’re asking the stars for clarity. Or memes.",
  15: "You’ve entered the 'what if' section of your memory.",
  16: "You’re romanticizing your own melancholy.",
  17: "You’re digesting the past in real time.",
  18: "Your playlist just guessed your mood correctly.",
  19: "You're typing something honest. Then deleting it.",
  20: "You're still in pajamas. Emotionally.",
  21: "Your evening is a poem in lowercase.",
  22: "You’re emotionally rearranging furniture in your mind.",
  23: "You feel something. You just don’t know what.",
  24: "7PM is golden hour for gentle spiraling.",
  25: "You made eye contact with your reflection too long.",
  26: "You’re scrolling to fill a quiet you can’t name.",
  27: "You're texting ghosts again.",
  28: "This hour is sponsored by unresolved emotions.",
  29: "You just stared at a wall and felt things.",
  30: "You're softer than you admit.",
  31: "You’re rewinding your day in silent fragments.",
  32: "You just sighed and called it therapy.",
  33: "This is the hour where pillows become confidants.",
  34: "You’ve typed 'how to feel better' more than once.",
  35: "You don’t want answers. Just acknowledgment.",
  36: "You're journaling mentally with no paper.",
  37: "This moment is held together with glowy thoughts.",
  38: "You're thinking about everything and texting no one.",
  39: "You’ve begun your nightly transformation into fog.",
  40: "Your soul is trying to schedule a nap.",
  41: "This hour tastes like warm silence.",
  42: "You’re craving eye contact and comfort food.",
  43: "You’ve entered emotional HDMI mode.",
  44: "Everything feels like a metaphor.",
  45: "You’re talking to yourself with respect.",
  46: "You’re dissolving beautifully into your evening.",
  47: "You're one warm light away from a breakthrough.",
  48: "You are moonlit confusion in a blanket.",
  49: "You’ve become ambient poetry with anxiety.",
  50: "You’re texting 'are you up?' to your regrets.",
  51: "You’re romanticizing quiet because it’s all you have.",
  52: "This hour hums like a love song to stillness.",
  53: "You’re not okay. But you’re aesthetically coping.",
  54: "You're surviving in soft focus.",
  55: "You’ve found peace in your mess.",
  56: "7PM is your artistic breakdown window.",
  57: "You're unsure if you’re tired or tragic.",
  58: "Everything's okay-ish. You’re okay-ish.",
  59: "This hour ends gently, with room for healing."
};

quotes[20] = {
  0: "8PM: the hour where soft chaos whispers.",
  1: "You are a quiet thought in motion.",
  2: "You're replying to messages with your eyes closed.",
  3: "Your brain has switched to moonlight mode.",
  4: "Everything now has the texture of memory.",
  5: "You’re winding down like a vintage record.",
  6: "You blink slower at this hour.",
  7: "You’re full of feelings, but politely quiet about it.",
  8: "Your evening voice is softer. More honest.",
  9: "You’re scrolling gently through your own mind.",
  10: "This hour hums with unanswered questions.",
  11: "You're the ghost of your 3PM self.",
  12: "You’re curling into your own presence.",
  13: "You just opened a new tab called 'what if.'",
  14: "This moment is scented like old warmth.",
  15: "You're processing more than you planned.",
  16: "You said ‘I’m fine’ with a candle in your soul.",
  17: "Even the fridge sounds emotional now.",
  18: "You’re listening to music like it’s advice.",
  19: "Your shadow is having thoughts without you.",
  20: "You’re texting friends in lowercase empathy.",
  21: "Your socks are off. So are your defenses.",
  22: "This hour is made of ellipses and tea.",
  23: "You’re speaking in sighs and snack metaphors.",
  24: "You just whispered ‘whatever’ to the ceiling.",
  25: "You're pretending to be okay. But artistically.",
  26: "You’ve become the closing scene of your own day.",
  27: "You stared at the wall and felt supported.",
  28: "You're three thoughts away from journaling.",
  29: "This is the quiet where growth hides.",
  30: "You remembered something beautiful. It stung.",
  31: "You’re ambient, like a fading memory.",
  32: "You’re emotionally tucked in.",
  33: "You are unsent messages in a hoodie.",
  34: "The playlist knows more than your therapist.",
  35: "You are a blurry poem with notifications off.",
  36: "You’re dancing with your past. Gently.",
  37: "You whispered ‘maybe tomorrow’ to your ambition.",
  38: "You are half-asleep and fully poetic.",
  39: "You paused to feel. It almost worked.",
  40: "You’ve become your own comfort zone.",
  41: "The room is full of your quiet echoes.",
  42: "You’ve reached gentle melancholy mode.",
  43: "You lit a candle in your mind and called it peace.",
  44: "This hour curls around your ankles like a cat.",
  45: "You're slowly unplugging from your public self.",
  46: "The world outside has faded. You’re still glowing.",
  47: "You’re humming nostalgia in lowercase.",
  48: "You're doing nothing. And it matters.",
  49: "You're not overthinking. You're gently processing.",
  50: "Everything is slower now. You included.",
  51: "You are emotional ambiance.",
  52: "You're mentally wrapped in string lights.",
  53: "This hour doesn’t need a reason.",
  54: "You're a cup of tea that hasn’t cooled yet.",
  55: "You're no longer chasing the day.",
  56: "Your softness is showing. Let it.",
  57: "You exhaled like it meant something.",
  58: "You survived today. Now you’re unraveling it.",
  59: "8PM is when you finally hear yourself."
};

quotes[21] = {
  0: "9PM: the gentle spiral begins.",
  1: "You’re not tired. You’re time-traveling backward in memory.",
  2: "This hour smells like laundry and thoughts.",
  3: "You’ve become a velvet version of yourself.",
  4: "Your body is still. Your mind is doing laps.",
  5: "You're mentally filing away unsaid things.",
  6: "You’ve romanticized your whole timeline by now.",
  7: "Everything is slow, deliberate, a little sad.",
  8: "You just sighed at the moon.",
  9: "You’re not in bed, but you’re halfway there emotionally.",
  10: "Your voice has become a whisper inside yourself.",
  11: "You’re thinking in scenes and soundtracks.",
  12: "You’ve texted no one, but drafted emotional essays.",
  13: "You are a memory rehearsing its lines.",
  14: "9PM is when the day untangles you.",
  15: "You paused your show because a feeling arrived.",
  16: "The window is just a mirror for your mood.",
  17: "You’ve rewritten that message three times and never sent it.",
  18: "You just held your phone like it meant something.",
  19: "You are the ghost of unsent messages.",
  20: "Everything quiet is a little too loud now.",
  21: "You are emotionally curled on a metaphorical couch.",
  22: "You’ve become extremely reflective with no resolution.",
  23: "You paused to think. You’re still paused.",
  24: "This hour exists in italics.",
  25: "You are half blanket, half nostalgia.",
  26: "You’re not crying. But you could if someone asked kindly.",
  27: "You’re speaking to no one in your head. With feeling.",
  28: "You are a painting of tired hope.",
  29: "Your silence is screaming in lowercase.",
  30: "You stopped multitasking and started remembering.",
  31: "You are now listening to your own heartbeat like it’s a podcast.",
  32: "The quiet has opinions.",
  33: "You're texting people in your mind again.",
  34: "You became poetry the moment you stopped trying.",
  35: "Your shadow is journaling.",
  36: "You are mourning and marveling. At the same time.",
  37: "You turned off the lights and turned on your thoughts.",
  38: "You sighed and the room agreed.",
  39: "You’ve been staring at the same sentence and it’s staring back.",
  40: "You became a soundtrack to your own stillness.",
  41: "You whispered something to yourself. It mattered.",
  42: "You’re looking for closure in the blanket folds.",
  43: "You exhaled like it meant goodbye.",
  44: "You are the candle flicker of this timeline.",
  45: "You haven’t moved. But you’ve traveled far inside.",
  46: "You typed 'I'm okay' and hoped it wasn’t a lie.",
  47: "You're hiding under layers of softness and sarcasm.",
  48: "This hour is lined with emotional velvet.",
  49: "You are not lost. Just dimmed.",
  50: "You are waiting for something and nothing.",
  51: "You laughed alone. It was honest.",
  52: "You’re quietly preparing to disappear into blankets.",
  53: "You're made of sighs and stillness now.",
  54: "Everything you feel is softly real.",
  55: "You’re resting in the ruins of your day.",
  56: "9PM is your truest self humming.",
  57: "You survived. Quietly. Completely.",
  58: "This is your hour of almosts.",
  59: "The world dimmed. You let it."
};

quotes[22] = {
  0: "10PM: the hour of sacred stillness.",
  1: "You’ve wrapped yourself in quiet like a blanket.",
  2: "Everything soft is louder now.",
  3: "You’re emotionally dimmed, but glowing.",
  4: "You whispered something to the darkness. It listened.",
  5: "You are floating in your own breath.",
  6: "This hour tastes like nostalgia and chamomile.",
  7: "Your body is horizontal. Your thoughts are not.",
  8: "You’ve entered the realm of whispered truths.",
  9: "You are one flicker away from sleep or clarity.",
  10: "This silence isn’t empty. It’s full of you.",
  11: "You’re lying down, but spiraling upright.",
  12: "Your blankets remember everything.",
  13: "You are emotionally toothbrushed and lightly haunted.",
  14: "The moon is your only witness now.",
  15: "You didn’t do it all. But you are still whole.",
  16: "This hour is an open tab for forgiveness.",
  17: "You are soft and mostly harmless tonight.",
  18: "You’re not tired. You’re unraveling gently.",
  19: "The lights are off. But your thoughts aren’t.",
  20: "You’ve whispered goodnight to everything but yourself.",
  21: "This is your slowest heartbeat of the day.",
  22: "You sighed and became the floor.",
  23: "You’ve become your truest voice — unspoken.",
  24: "You’re letting go in invisible ways.",
  25: "You don’t need words. Just rest.",
  26: "Even your shadows feel calm now.",
  27: "Your regrets are curled up beside you.",
  28: "This hour is wrapped in wool and memory.",
  29: "You’re no longer pretending anything.",
  30: "You are a slow poem written in breath.",
  31: "You whispered 'maybe tomorrow' and meant it.",
  32: "You blinked and forgave yourself a little.",
  33: "The clock is quiet. So are your doubts.",
  34: "You’ve grown tired of fighting yourself.",
  35: "You are nothing but a soft echo now.",
  36: "You let go of expectations. Finally.",
  37: "This hour asks nothing. And gives everything.",
  38: "You’re healing by doing absolutely nothing.",
  39: "Your bed knows more than your calendar ever did.",
  40: "You are the night’s favorite secret.",
  41: "Your past cannot find you here.",
  42: "You’ve shut down without shame.",
  43: "You deserve this hour. Fully.",
  44: "Your inner world is rocking you to sleep.",
  45: "You are off-duty and deeply yourself.",
  46: "The day is over. You are not.",
  47: "Your softness is finally safe.",
  48: "You’ve earned this absence of noise.",
  49: "You are the dot after a long sentence.",
  50: "Everything can wait. Even your worries know that now.",
  51: "You are simply existing. That’s more than enough.",
  52: "You’ve closed every tab but your eyes.",
  53: "10PM is for breathing you didn’t know you needed.",
  54: "You are silent applause in a room of one.",
  55: "You let yourself be unfinished.",
  56: "The world is dim, and so are your fears.",
  57: "You’ve survived the noise. Now comes the hum.",
  58: "You don’t need closure tonight. Just rest.",
  59: "This hour is holding you without asking anything."
};

quotes[23] = {
  0: "11PM: the hour of honest shadows.",
  1: "You are the last light still flickering.",
  2: "This hour hums in lowercase and longing.",
  3: "You’ve become your own bedtime story.",
  4: "You’re not ready for sleep. Just silence.",
  5: "Everything feels raw, but poetic.",
  6: "You're halfway to dreaming. Fully feeling.",
  7: "You’ve stopped trying to make sense. Good.",
  8: "This hour knows your real name.",
  9: "You whispered a truth into your pillow.",
  10: "You are dissolving gently into softness.",
  11: "You’ve entered your own private ocean.",
  12: "This darkness is the kind that holds you.",
  13: "You are floating beneath your own surface.",
  14: "Your soul is curling up in corners.",
  15: "Everything undone will wait till dawn.",
  16: "You are glowing in emotional grayscale.",
  17: "The world has stopped looking. You can rest.",
  18: "This moment doesn’t need an audience.",
  19: "You said goodnight to the chaos. Finally.",
  20: "You’re emotionally untied. Let it be.",
  21: "You are holding nothing. And still whole.",
  22: "You sighed and something healed.",
  23: "You don’t need the stars. Just stillness.",
  24: "The clock ticks, but you don’t have to.",
  25: "This is the slowest kind of magic.",
  26: "You closed your eyes. The past blinked too.",
  27: "You are a love letter never sent.",
  28: "You’re made of hush and forgiveness.",
  29: "You do not need to prove anything right now.",
  30: "You’ve muted the world to hear yourself again.",
  31: "This hour drapes you in invisible velvet.",
  32: "You're doing nothing. And it's beautiful.",
  33: "You’ve become one long breath in the dark.",
  34: "Your inner voice is curled beside you.",
  35: "Nothing left to say. Only to rest.",
  36: "You are forgiven, even by yourself.",
  37: "11PM: your final exhale of the day.",
  38: "You are the silence between songs.",
  39: "You are resting in your own name.",
  40: "No need to think. Just float.",
  41: "You're made of quiet bravery.",
  42: "Your sadness has softened. Let it stay a while.",
  43: "You don’t need to fix. Just be.",
  44: "You are a poem with the lights off.",
  45: "You are not the work. You are the wonder.",
  46: "You made it. That’s enough story for today.",
  47: "This hour wraps you like a secret.",
  48: "Nothing makes sense, and that’s peace.",
  49: "You’re finally your own permission slip.",
  50: "Sleep is rebellion. You’ve earned it.",
  51: "Let go. The stars already have.",
  52: "You are safe in your silence.",
  53: "Everything paused. So can you.",
  54: "You're not alone. You’re with yourself.",
  55: "This moment doesn’t need to be perfect.",
  56: "You’ve gone quiet in all the best ways.",
  57: "Your softness is your revolution.",
  58: "Tomorrow is far away. Stay here.",
  59: "The day is done. And so are you. Gently."
};



function updateClock() {
  let now = new Date();
  let hour = now.getHours();
  let minute = now.getMinutes();
  let ampm = hour >= 12 ? "PM" : "AM";
  let hour12 = hour % 12 === 0 ? 12 : hour % 12;

  timeEl.innerText = hour12 + ":" + String(minute).padStart(2, "0") + " " + ampm;

  if (hour >= 5 && hour < 11) {
    periodEl.innerText = "morning";
    document.body.style.backgroundColor = "#FFFBDA";
    bar.style.backgroundColor = "#FFB347";
    timeEl.style.color = "#FF9248";
    quoteEl.style.color = "#333333";
    document.querySelector(".line1").style.color = "#333333";
    document.querySelector(".line2").style.color = "#333333";
  } else if (hour >= 11 && hour < 17) {
    periodEl.innerText = "afternoon";
    document.body.style.backgroundColor = "#FFF3E2";
    bar.style.backgroundColor = "#FF5A36";
    timeEl.style.color = "#FF5A36";
    quoteEl.style.color = "#222222";
    document.querySelector(".line1").style.color = "#222222";
    document.querySelector(".line2").style.color = "#222222";
  } else if (hour >= 17 && hour < 20) {
    periodEl.innerText = "evening";
    document.body.style.backgroundColor = "#F7D4BC";
    bar.style.backgroundColor = "#D8572A";
    timeEl.style.color = "#D8572A";
    quoteEl.style.color = "#2D1C16";
    document.querySelector(".line1").style.color = "#2D1C16";
    document.querySelector(".line2").style.color = "#2D1C16";
  } else {
    periodEl.innerText = "nighttime";
    document.body.style.backgroundColor = "#1E1E3F";
    bar.style.backgroundColor = "#85C1E9";
    timeEl.style.color = "#85C1E9";
    quoteEl.style.color = "#FDFD96";
    document.querySelector(".line1").style.color = "#ffffff";
    document.querySelector(".line2").style.color = "#ffffff";
  }

  if (quotes[hour] && quotes[hour][minute]) {
    quoteEl.innerHTML = "“" + quotes[hour][minute] + "”";
  } else {
    quoteEl.innerHTML = "“Generic quote for now.<br>You’ll live.”";
  }

  scaleToFit();
}

function scaleToFit() {
  let parent = document.querySelector(".outer");
  let scaleTarget = content;
  scaleTarget.style.transform = "scale(1)";
  let scaleX = parent.offsetWidth / scaleTarget.offsetWidth;
  let scaleY = parent.offsetHeight / scaleTarget.offsetHeight;
  let scale = Math.min(scaleX, scaleY);
  scaleTarget.style.transform = "scale(" + scale + ")";
}

function updateMinuteBar() {
  let now = new Date();
  let totalMs = now.getSeconds() * 1000 + now.getMilliseconds();
  let mappedWidth = map(totalMs, 0, 60000, 0, 100);
  bar.style.width = mappedWidth + "%";
}

function animateBar() {
  updateMinuteBar();
  requestAnimationFrame(animateBar);
}

function map(value, low1, high1, low2, high2) {
  return low2 + (high2 - low2) * (value - low1) / (high1 - low1);
}

window.onload = function () {
  updateClock();
  scaleToFit();
  updateMinuteBar();
  setInterval(updateClock, 1000);
  window.addEventListener("resize", scaleToFit);
  animateBar();
};
